<a href="https://colab.research.google.com/github/deepakmeena61/Digit-Recognition/blob/main/Digit_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 Programming Problem 1:
Simple convolutional neural networks (CNN) USING Tensorflow and Keras

1.1 Loading dataset and building input pipelines

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

In [ ]:
#(ds_trn, ds_vld, ds_tst), ds_info = tfds.load(name = 'mnist', 
#                                      split = ["train[10%:]", "train[0%:10%]", "test"],
#                                      shuffle_files = True , 
#                                     as_supervised = True,
#                                      with_info = True)

In [ ]:
mnist = tf.keras.datasets.mnist
(x_t, y_t),(X_test, y_test) = mnist.load_data()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(x_t, y_t, test_size=0.10, 
                                                    random_state=42)

In [ ]:
print("Train set size: ", len(X_train))

Train set size:  54000


In [ ]:
print("Test set size: ", len(X_test))

Test set size:  10000


In [ ]:
print("Validation set size: ", len(X_valid))

Validation set size:  6000


In [ ]:
print(X_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [ ]:
print(y_train)

[1 6 6 ... 0 0 4]


In [ ]:
#Normalize input images
def normalize_image(x):
  img = tf.cast(x , tf.float32)/255.0
  return img

In [ ]:
X_train = normalize_image(X_train)


In [ ]:
X_valid = normalize_image(X_valid)

In [ ]:
X_test = normalize_image(X_test)

1.2 Define CNN Network Model

In [ ]:
model_1 = tf.keras.Sequential()
model_1.add(tf.keras.layers.Conv2D(32, kernel_size = (3,3), 
                                   activation = 'relu', 
                                   strides = (1,1),
                                   input_shape = (28,28,1),
                                   padding = 'same'))
model_1.add(tf.keras.layers.Conv2D(64, kernel_size = (3,3), 
                                   activation = 'relu', 
                                   strides = (1,1),
                                   padding = 'same'))
model_1.add(tf.keras.layers.MaxPool2D())
model_1.add(tf.keras.layers.Flatten())
model_1.add(tf.keras.layers.Dense(256, activation = 'relu'))
model_1.add(tf.keras.layers.Dense(128, activation = 'softmax'))

1.3 Compile CNN model

In [ ]:
model_1.compile(loss = tf.keras.losses.sparse_categorical_crossentropy, 
                optimizer = tf.keras.optimizers.experimental.Nadam(),
                metrics = ['accuracy'])

1.4 Train CNN

In [ ]:
model_cnn = model_1.fit(x = X_train, y = y_train, epochs = 6)
print("Model successfully trained")

Epoch 1/6
1688/1688 [==============================] - 277s 163ms/step - loss: 0.1889 - accuracy: 0.9619
Epoch 2/6
1688/1688 [==============================] - 261s 155ms/step - loss: 0.0457 - accuracy: 0.9854
Epoch 3/6
1688/1688 [==============================] - 260s 154ms/step - loss: 0.0334 - accuracy: 0.9898
Epoch 4/6
1688/1688 [==============================] - 263s 156ms/step - loss: 0.0298 - accuracy: 0.9911
Epoch 5/6
1688/1688 [==============================] - 256s 152ms/step - loss: 0.0262 - accuracy: 0.9919
Epoch 6/6
1688/1688 [==============================] - 255s 151ms/step - loss: 0.0189 - accuracy: 0.9944
Model successfully trained


In [ ]:
model_1.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 28, 28, 32)        320       
                                                                 
 conv2d_7 (Conv2D)           (None, 28, 28, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 14, 14, 64)       0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 12544)             0         
                                                                 
 dense_6 (Dense)             (None, 256)               3211520   
                                                                 
 dense_7 (Dense)             (None, 128)               32896     
                                                      

In [ ]:
valid_loss, valid_acc = model_1.evaluate(x = X_valid, y = y_valid)
print('\nValidation accuracy:', valid_acc)

188/188 [==============================] - 7s 34ms/step - loss: 0.0913 - accuracy: 0.9837

Validation accuracy: 0.9836666584014893


1.5 Evaluate test set performance

In [ ]:
test_loss, test_acc = model_1.evaluate(x = X_test, y = y_test)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 12s 38ms/step - loss: 0.0829 - accuracy: 0.9822

Test accuracy: 0.982200026512146


# Back deep feedforward MLP network, using Tensorflow and Keras

2.1 Define a simple deep MLP network model

In [ ]:
model_2