<a href="https://colab.research.google.com/github/deepakmeena61/Digit-Recognition/blob/main/Digit_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 Programming Problem 1:
Simple convolutional neural networks (CNN) USING Tensorflow and Keras

1.1 Loading dataset and building input pipelines

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

In [2]:
#(ds_trn, ds_vld, ds_tst), ds_info = tfds.load(name = 'mnist', 
#                                      split = ["train[10%:]", "train[0%:10%]", "test"],
#                                      shuffle_files = True , 
#                                     as_supervised = True,
#                                      with_info = True)

In [3]:
mnist = tf.keras.datasets.mnist
(x_t, y_t),(X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(x_t, y_t, test_size=0.10, 
                                                    random_state=42)

In [5]:
print("Train set size: ", len(X_train))

Train set size:  54000


In [6]:
print("Test set size: ", len(X_test))

Test set size:  10000


In [7]:
print("Validation set size: ", len(X_valid))

Validation set size:  6000


In [8]:
print(X_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [9]:
print(y_train)

[1 6 6 ... 0 0 4]


In [10]:
#Normalize input images
def normalize_image(x):
     img = x.astype('float32')/255.0
     return img

In [11]:
X_train = normalize_image(X_train)


In [12]:
X_valid = normalize_image(X_valid)

In [13]:
X_test = normalize_image(X_test)

1.2 Define CNN Network Model

In [14]:
model_1 = tf.keras.Sequential()
model_1.add(tf.keras.layers.Conv2D(32, kernel_size = (3,3), 
                                   activation = 'relu', 
                                   strides = (1,1),
                                   input_shape = (28,28,1),
                                   padding = 'same'))
model_1.add(tf.keras.layers.Conv2D(64, kernel_size = (3,3), 
                                   activation = 'relu', 
                                   strides = (1,1),
                                   padding = 'same'))
model_1.add(tf.keras.layers.MaxPool2D())
model_1.add(tf.keras.layers.Flatten())
model_1.add(tf.keras.layers.Dense(32, activation = 'relu'))
model_1.add(tf.keras.layers.Dense(10, activation = 'softmax'))

1.3 Compile CNN model

In [15]:
model_1.compile(loss = tf.keras.losses.sparse_categorical_crossentropy, 
                optimizer = tf.keras.optimizers.experimental.Nadam(),
                metrics = ['accuracy'])

1.4 Train CNN

In [16]:
model_cnn = model_1.fit(x = X_train, y = y_train, epochs = 6)
print("Model successfully trained")

Epoch 1/6
1688/1688 [==============================] - 22s 5ms/step - loss: 0.1427 - accuracy: 0.9574
Epoch 2/6
1688/1688 [==============================] - 8s 5ms/step - loss: 0.0487 - accuracy: 0.9854
Epoch 3/6
1688/1688 [==============================] - 8s 5ms/step - loss: 0.0322 - accuracy: 0.9898
Epoch 4/6
1688/1688 [==============================] - 8s 5ms/step - loss: 0.0236 - accuracy: 0.9922
Epoch 5/6
1688/1688 [==============================] - 8s 5ms/step - loss: 0.0167 - accuracy: 0.9945
Epoch 6/6
1688/1688 [==============================] - 8s 5ms/step - loss: 0.0127 - accuracy: 0.9960
Model successfully trained


In [17]:
model_1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 32)        320       
                                                                 
 conv2d_1 (Conv2D)           (None, 28, 28, 64)        18496     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 14, 14, 64)       0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 12544)             0         
                                                                 
 dense (Dense)               (None, 32)                401440    
                                                                 
 dense_1 (Dense)             (None, 10)                330       
                                                        

In [18]:
valid_loss, valid_acc = model_1.evaluate(x = X_valid, y = y_valid)
print('\nValidation accuracy:', valid_acc)

188/188 [==============================] - 1s 3ms/step - loss: 0.0509 - accuracy: 0.9892

Validation accuracy: 0.9891666769981384


1.5 Evaluate test set performance

In [19]:
test_loss, test_acc = model_1.evaluate(x = X_test, y = y_test)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0442 - accuracy: 0.9868

Test accuracy: 0.9868000149726868


# Back deep feedforward MLP network, using Tensorflow and Keras

2.1 Define a simple deep MLP network model

In [20]:
model_2 = tf.keras.Sequential()
model_2.add(tf.keras.layers.Flatten(input_shape = (28,28)))
model_2.add(tf.keras.layers.Dense(300, activation = 'relu'))
model_2.add(tf.keras.layers.Dense(100, activation = 'relu'))
model_2.add(tf.keras.layers.Dense(10, activation = 'softmax'))

2.2 Compile, train and evaluate this network

In [21]:
model_2.compile(loss = tf.keras.losses.sparse_categorical_crossentropy,
                optimizer = tf.keras.optimizers.experimental.Nadam(),
                metrics = ['accuracy'])

In [22]:
model_2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 300)               235500    
                                                                 
 dense_3 (Dense)             (None, 100)               30100     
                                                                 
 dense_4 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [23]:
model_hdl = model_2.fit(x = X_train, y = y_train, epochs = 6)
print("Model successfully trained")

Epoch 1/6
1688/1688 [==============================] - 8s 4ms/step - loss: 0.2097 - accuracy: 0.9387
Epoch 2/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0874 - accuracy: 0.9734
Epoch 3/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0583 - accuracy: 0.9810
Epoch 4/6
1688/1688 [==============================] - 6s 3ms/step - loss: 0.0442 - accuracy: 0.9853
Epoch 5/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0334 - accuracy: 0.9886
Epoch 6/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0279 - accuracy: 0.9911
Model successfully trained


In [24]:
valid_loss, valid_acc = model_2.evaluate(x = X_valid, y = y_valid)
print('\nValidation accuracy:', valid_acc)

188/188 [==============================] - 1s 3ms/step - loss: 0.0816 - accuracy: 0.9805

Validation accuracy: 0.9804999828338623


In [25]:
test_loss, test_acc = model_2.evaluate(x = X_test, y = y_test)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0804 - accuracy: 0.9783

Test accuracy: 0.9782999753952026


# Single hidden layer feedforward MLP network, using Tensorow and Keras


3.1 Dene a single hidden layer feedforward network model

In [26]:
model_3 = tf.keras.Sequential()
model_3.add(tf.keras.layers.Flatten(input_shape = (28,28)))
model_3.add(tf.keras.layers.Dense(100, activation = 'relu'))
model_3.add(tf.keras.layers.Dense(10, activation = 'softmax'))

3.2 Compile, train and evaluate this network


In [27]:
model_3.compile(loss = tf.keras.losses.sparse_categorical_crossentropy,
                optimizer = tf.keras.optimizers.experimental.Nadam(),
                metrics = ['accuracy'])

In [28]:
model_3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 100)               78500     
                                                                 
 dense_6 (Dense)             (None, 10)                1010      
                                                                 
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________


In [29]:
model_shl = model_3.fit(x = X_train, y = y_train, epochs = 6)
print("Model successfully trained")

Epoch 1/6
1688/1688 [==============================] - 6s 3ms/step - loss: 0.2919 - accuracy: 0.9167
Epoch 2/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.1297 - accuracy: 0.9623
Epoch 3/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0903 - accuracy: 0.9736
Epoch 4/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0684 - accuracy: 0.9797
Epoch 5/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0543 - accuracy: 0.9834
Epoch 6/6
1688/1688 [==============================] - 5s 3ms/step - loss: 0.0443 - accuracy: 0.9869
Model successfully trained


In [30]:
valid_loss, valid_acc = model_3.evaluate(x = X_valid, y = y_valid)
print('\nValidation accuracy:', valid_acc)

188/188 [==============================] - 1s 3ms/step - loss: 0.0766 - accuracy: 0.9780

Validation accuracy: 0.9779999852180481


In [31]:
test_loss, test_acc = model_3.evaluate(x = X_test, y = y_test)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0798 - accuracy: 0.9752

Test accuracy: 0.9751999974250793
